### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by cadriel** [mchilli/macropad#1]
- Allow an easy way to copy / paste color codes between groups / macros. Currently I can't paste one hex code to another for example.
- Allow the use of icons for labels.
- Allow the default encoder function on the home / first page

**Comment by mchilli** [comment]
- Yes, I noticed that too. I think it's strange behavior of the default chrome color picker (or a bug?). Maybe it would be nice to have a second input next to the color picker where you can copy or paste the hex code.
- I hope you mean something like Unicode symbols. Maybe I can use [this font](https://www.cl.cam.ac.uk/~mgk25/ucs-fonts.html) to support unicode characters.
- Yes, I think this would be nice, but where can this be configured in a nice way?!

**Comment by cadriel** [comment]
Thanks a bunch for pushing this in so quick! :)
