### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by cadriel** [mchilli/macropad#3]
An idea to remove the void middle top button;

Instead of forcing the navigation to take up the top row - allow the user to define how they want to navigate between groups.

I.e., we can already place a group anywhere. You could add some new macro types / controls;
- Go back (steps back a level)
- Go to specific group (Allows you to jump to a group)

This way users could make use of the top row in any way they want. It also removes the need to have a voided button.

**Comment by mchilli** [comment]
Ok, to be honest, I don't like it when, in the worst case, the user can prevent himself from navigating by forgetting to configure the navigation buttons.
My idea was originally to use it as a kind of home button. To get from whatever group back to the root group.

**Comment by cadriel** [comment]
So, that's still ok - you could still provide what I suggested - and default the top left button to the home / root group.

I guess in that case you could also allow the user to override this if they want to. Also - what happens when you have 3 group levels deep, isn't the home button then going to be a bit ambiguous?

**Comment by mchilli** [comment]
Yes, that's why I haven't implemented this yet. Does “Home” mean the first page in a group or the very first group?!

Sure, I could create a device function that works the same as the navigation buttons. But why when there are navigation buttons?
On the other hand, that means I would have to rewrite the underlying code structure even though I don't want to use it that way. Sorry.

**Comment by cadriel** [comment]
Sure, this is entirely up to you. :)

IMO - I don't use the navigation buttons to move forward and backwards on the macro pad either. In my ideal setup, I have a page of macros - and I have control on how I navigate them.

The positive here is that I don't lose control of any buttons, and have complete control of the layout.

You can close this if you don't want to adjust how you navigate tho. :)

**Comment by mchilli** [comment]
You mean get rid of the whole page concept and only use groups for navigation? I think I know what you mean now. That's interesting! But I think that's a lot of work, not only for the Circuitpython base, but also for the WebUI. Because it changes my whole concept.
Maybe I will think about it and leave this issue open.

**Comment by cadriel** [comment]
One good example is how QMK does it;

I.e., your layer 0 is full of groups. When you enter a group - you move to that layer (say, layer 1 for example). On layer one - you have all of your macro's, but the top left button is assigned to go back to layer 0.

You could also stack groups - so have more groups on layer 1 too.

This makes navigating intuitive - but also gives flexibility.

Also, with QMK you can also replicate your navigation. I.e., on layer 0 the top left button could be set to go to layer 9 - and the top right button to go to layer 1.

Anyway, some more thoughts to help think it through :)

**Comment by mchilli** [comment]
Hey, I created a "group-concept" branch where I created a first webui test to show the concept I'm thinking about.
There are now 12 keys and no more pages. When you create a group and open it, a "close macro" is automatically inserted, which can be clicked to close the group. The label, colour and position can be defined, but it cannot be deleted. 
If you have some time, can you have a look and tell me what you think?

**Comment by cadriel** [comment]
Absolutely. I'll give it a shot a bit later today and let you know.

**Comment by cadriel** [comment]
So, this works pretty well I think.

It basically replicates what I have setup locally - but now I can make use of all rows of keys, so I feel like this is a really nice improvement.

Its also nice that people can now decide where they want their "back" button too - plus, they can still nest macro groups as deep as they want.

The only thing you might want to consider is giving users the ability to "go to root". I.e., perhaps people setup macro groups 3 levels deep, and want an easy way to go right back to level 0 - but its not strictly necessary.

**Comment by mchilli** [comment]
But there are still some unanswered questions. For example, where is the current group shown on the small display? I am also still thinking about whether to continue using the button to the left of the group settings for "back". But if you can click the button directly, that becomes kind of irrelevant. Especially if you use a "back to root" setting. Also the question of whether something should be built in that converts the old configurations to the new concept?

**Comment by cadriel** [comment]
Ok, here's some thoughts;

1.
Update the python / JSON to support any layout. For example, at the moment - your python code has forced, built-in macro navigation. Instead of this - have the configuration of buttons entirely configured via the JSON.

This means you can conceivably create ANY layout and navigation just with the JSON file, rather than having to update the python code. You would need to support buttons like home, root etc.

Also - if your JSON format allows listing all configured macro groups, then you can still support the "next page, previous page" paradigm if you want. Secondarily people could bind the knob to move through the pages.

2.
With the above in mind, the LCD should support 5 rows. The top row could display the layer / group name. The other 4 rows are the configured buttons. Here's a good image representing one option for that;
https://blog.adafruit.com/2021/09/02/case-for-macropad-rp2040-3dprinting-3dthursday/

3.
Finally - this means your Web UI becomes the master record / dictator of how the macro pad works. If you want to implement a new way of navigation, then the python code doesn't prevent you from doing so.

All of the above also has the added benefit that more technical people can simply edit the JSON by hand and do what they want.

4.
Personally, I wouldn't bother with a config conversion. Make it a major release - and note that it will break old configurations. If this is a real concern for you, then you might want to build that in to the web UI.

**Comment by cadriel** [comment]
fwiw - i might be able to help out with the web configurator given the above if that helps.

**Comment by mchilli** [comment]
1. so I updated the python code! There is no toolbar anymore. I got rid of the whole concept of pages, if someone wants something like that, they can for example create a group within a group and call it "page 2" or something. Now there are two new system functions ("close_group" and "go_to_root") for navigation.

2. I added a fifth line for the group label. This makes the buttons more squeezed together, sadly, but ok for me.

3. that's a fact! I added two new types ("close", "root"), this works for now, but I don't like it. I want them to be macros too, technically they work like that. But I have no idea how to separate them from other macros in the webui, e.g. to configure them or how their behaviour is in the webui.

4. I added a conversion function in the webui. And maybe I add a hint that you have to convert the old file in the webui first before updating the macropad.

Could you maybe test the current state in the "group-concept" branch. To fix possible bugs?

It's nice if you want to help. So if you have some ideas with the problem in point 3, it would help me a lot!!!

**Comment by cadriel** [comment]
This looks really good, and seems to work well for me.

The one thing that is weird is that you can add a macro called 'device function' -> 'go_to_root' or 'go_back', which makes sense. But the automatically added item isn't the same thing.

Why not have the automatic go back configured as a macro? This way it looks the same as if someone had configured it themselves. You could add some kind of flag in the json to determine if an item is editable if you don't want people deleting it.

Otherwise, all looks good!

**Comment by mchilli** [comment]
As I explained in my last post, both are technically the same. But to separate how they work in the webui ("close the group" or "go to root") I gave them the type "close" or "group". This allows me to show other things in the dialog and hide the delete button. But I don't really like that. I'm looking for a more modular solution where I can just add more if I want.

**Comment by mchilli** [comment]
Hey, I think I have a robust modular solution now. Can you give it one last try before I merge it?
