### ISSUE TITLE
Allow brightness adjustment

### ISSUE THREAD

**Issue by cadriel** [mchilli/macropad#5]
Allow the user to adjust the brightness of all keys (perhaps a setting..)

**Comment by mchilli** [comment]
This is currently already possible under device functions. The brightness is not saved at the moment, but I think I can implement it, if you want?!

**Comment by cadriel** [comment]
I find the full brightness to be really too much in darker conditions.. so having the ability to save the default brightness would be great.

**Comment by mchilli** [comment]
Yes you are right. For this reason I set the default brightness to the lowest it can reach before it turns off. Keep this in mind, it will not get any darker.
