### ISSUE TITLE
Allow rotation

### ISSUE THREAD

**Issue by cadriel** [mchilli/macropad#6]
Allow the user to orient the macro pad how they want. I.e., I want it rotated (so rotary knob on the bottom..).

**Comment by mchilli** [comment]
If you mean rotate 0 or 180 degree, this should be done relatively easy.

**Comment by cadriel** [comment]
180 for me, but maybe have the option for all 4 rotations?

**Comment by mchilli** [comment]
I have tested 90 and 270 degrees and it looks terrible! There is not enough space on the display at this rotation. So let's call it "flip orientation" or so, and implement it.

**Comment by cadriel** [comment]
Ah yes, sounds good! I didn't think about the size of the screen at 90 and 270 :D
